spring:
  profiles:
    active: test-postgresql
---
spring:
  config:
    activate:
      on-profile: test-postgresql
  datasource:
    url:
  data:
    jpa:
      hibernate:
        ddl-auto: create
      properties:
        hibernate:
          format_sql: true
          use_sql_comments: true
logging:
  level: debug